version: '3.5'

services:
  spark-master:
    container_name: spark-master
    image: guanyili/spark-master:0.0.1
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net
    restart: unless-stopped
  
  spark-worker-1:
    container_name: spark-worker-1
    image: guanyili/spark-worker:0.0.1
    environment:
      MASTER_CONTAINER_NAME: spark-master
    ports:
      - "8081:8081"
    networks:
      - spark-net
    depends_on:
      - spark-master
    restart: unless-stopped
  
  spark-worker-2:
    container_name: spark-worker-2
    image: guanyili/spark-worker:0.0.1
    environment:
      MASTER_CONTAINER_NAME: spark-master
    ports:
      - "8082:8081"
    networks:
      - spark-net
    depends_on:
      - spark-master
    restart: unless-stopped

networks:
  spark-net:
    driver: bridge