version: '3.5'

services:
  spark-worker-1:
    image: guanyili/spark-worker-pi
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    restart: unless-stopped
    volumes:
      - /data/spark/workspace:/opt/workspace